Option Explicit

Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean

Sub main()

    Set swApp = Application.SldWorks
    
    ' --- Kapı Kasası ---
    Set Part = swApp.NewDocument("C:\ProgramData\SolidWorks\SOLIDWORKS 2022\templates\Part.prtdot", 0, 0, 0)
    Part.SketchManager.InsertSketch True
    Part.SketchManager.CreateCenterRectangle 0, 0, 0, 0.45, 1.05, 0   ' 90x210 cm kasa içi
    Part.FeatureManager.FeatureExtrusion2 True, False, False, 0, 0, 0.08, 0, False, False, False, False, _
    0, 0, False, False, False, False, True, True, True, 0, 0, False
    
    swApp.SendMsgToUser "Kasa oluşturuldu"

    ' --- Kapı Kanadı ---
    Part.SketchManager.InsertSketch True
    Part.SketchManager.CreateCenterRectangle 0, 0, 0, 0.43, 1.03, 0
    Part.FeatureManager.FeatureExtrusion2 True, False, False, 0, 0, 0.07, 0, False, False, False, False, _
    0, 0, False, False, False, False, True, True, True, 0, 0, False
    
    swApp.SendMsgToUser "Kapı kanadı oluşturuldu"
    
' --- Kilit Yuvası ---
Dim swSketch As Sketch

' Yeni skeç başlat
Part.SketchManager.InsertSketch True

' Dikdörtgen çiz (merkez dikdörtgen)
Part.SketchManager.CreateCenterRectangle 0.39, 0.025, 0, 0.02, 0.025, 0

' Skeçi bitir
Part.SketchManager.InsertSketch True

' Extruded Cut (Kesit)
Dim swFeat As Feature
Set swFeat = Part.FeatureManager.FeatureCut3(True, False, False, _
    0, 0, 0.02, 0, _
    False, False, False, False, _
    0, 0, _
    False, False, False, False, _
    True, True, True, True, _
    False, 0, 0, False)

    
    ' --- Menteşe Yerleri ---
    Part.SketchManager.InsertSketch True
    Part.SketchManager.CreateCircle 0, 1, 0, 0.02, 1, 0
    Part.FeatureManager.FeatureCut3 True, False, False, 0, 0, 0.02, 0, False, False, False, False, _
    0, 0, False, False, False, False, True, True, True, True, False, 0, 0, False
    
    Part.SketchManager.CreateCircle 0, -1, 0, 0.02, -1, 0
    Part.FeatureManager.FeatureCut3 True, False, False, 0, 0, 0.02, 0, False, False, False, False, _
    0, 0, False, False, False, False, True, True, True, True, False, 0, 0, False
    
    swApp.SendMsgToUser "Menteşe yerleri açıldı"
    
    swApp.SendMsgToUser "Tam fonksiyonlu kapı modeli hazır!"
    
End Sub
